version: '3.9'
services:
  curso_node_ew:
    container_name: curso_node_ew
    build: .
    ports: 
      - "8080:8080"
    volumes: 
      - .:/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
