version: '3.9'
services:
  curso_node_ew:
    container_name: curso_node_ew
    build: .
    ports: 
      - "8080:8080"
    volumes: 
      - .:/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - mongo
    networks:
      - pg-network
  adminer:
    image: adminer
    container_name: adminer_sgbd
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always
    networks:
      - pg-network
  db:
    image: postgres:latest
    container_name: ew_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=heroes
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - pg-network
    volumes:
      - dba:/var/lib/postgresql
  mongo_client:
    image: mongoclient/mongoclient
    container_name: mongo_client
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo_database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - dba:/data/db

volumes:
  dba:

networks:
  pg-network:
    driver: bridge